version: '3.1'

name: prototype-masstransit

services:  
  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 10
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"                